remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

# Site Settings
title: StretchView
description: Ultimate Video Aspect Ratio Controller for Chrome
show_downloads: true

# Configure relative links
relative_links:
  enabled: true
  collections: true
